baseURL = 'https://mrpark97.github.io/master/'
languageCode = 'en-us'
title = 'Master'
theme = 'early-roman'
paginate= 6
googleAnalytics = 'G-H2Y2NCSZP8'

[params]
  yandexMetrika = 87079237

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 3